repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: .backend/venv/bin/black
        language: system
        types: [python]

      - id: ruff
        name: ruff
        entry: .backend/venv/bin/ruff
        language: system
        types: [python]