version: '3.8'

services:
  postgresql:
    container_name: ff15_postgresql
    image: bitnami/postgresql:17.2.0
    ports:
     - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  backend:
    container_name: ff15_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - postgresql

  frontend:
    container_name: ff15_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - backend
   
volumes:
  postgresql_data:
    driver: local