version: '3.8'

services:
  postgresql:
    container_name: ff15_postgresql
    image: bitnami/postgresql:16.4.0
    ports:
     - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - ./database:/docker-entrypoint-initdb.d
   
volumes:
  postgresql_data:
    driver: local