version: '3.8'

services:
  postgresql:
    container_name: ff15_postgresql
    image: bitnami/postgresql:17.2.0
    ports:
     - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
   
volumes:
  postgresql_data:
    driver: local