name: Testing

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  lint_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies for linting
      run: |
        pip install black ruff

    - name: Run Black
      run: |
        black --check backend

    - name: Run Ruff
      run: |
        ruff check backend --exit-zero
  lint_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Change to frontend directory
      run: cd frontend

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run ESLint
      working-directory: ./frontend
      run: npx eslint .

  test-backend:
      runs-on: ubuntu-latest
      needs: lint_backend
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12.4'
  
        - name: Install dependencies
          run: |
            cd backend
            python -m pip install --upgrade pip
            pip install -r requirements.txt          
  
        - name: Run tests
          env:
            #### Variables ####
            DOMAIN_EUROPE: ${{ vars.DOMAIN_EUROPE }}
            DOMAIN_AMERICAS: ${{ vars.DOMAIN_AMERICAS }}
            DOMAIN_ASIA: ${{ vars.DOMAIN_ASIA }}
            DOMAIN_SEA: ${{ vars.DOMAIN_SEA }}
            DOMAIN_ESPORTS: ${{ vars.DOMAIN_ESPORTS }}
  
            #Domains for SPECTATOR, SUMMONER, status, lol-challanges, league, league-exp, clash, champion
            DOMAIN_BR: ${{ vars.DOMAIN_BR }}
            #EUNE is EUN1 officialy
            DOMAIN_EUNE: ${{ vars.DOMAIN_EUNE }}
            DOMAIN_EUW: ${{ vars.DOMAIN_EUW }}
            DOMAIN_JP: ${{ vars.DOMAIN_JP }}
            DOMAIN_KR: ${{ vars.DOMAIN_KR }}
            #LAN is LA1 officialy
            DOMAIN_LAN: ${{ vars.DOMAIN_LAN }}
            #LAS is LA2 officialy
            DOMAIN_LAS: ${{ vars.DOMAIN_LAS }}
            DOMAIN_ME: ${{ vars.DOMAIN_ME }}
            DOMAIN_NA: ${{ vars.DOMAIN_NA }}
            #OCE is OC1 offcially
            DOMAIN_OCE: ${{ vars.DOMAIN_OCE }}
            DOMAIN_PH: ${{ vars.DOMAIN_PH }}
            DOMAIN_RU: ${{ vars.DOMAIN_RU }}
            DOMAIN_SG: ${{ vars.DOMAIN_SG }}
            DOMAIN_TH: ${{ vars.DOMAIN_TH }}
            DOMAIN_TR: ${{ vars.DOMAIN_TR }}
            DOMAIN_TW: ${{ vars.DOMAIN_TW }}
            DOMAIN_VN: ${{ vars.DOMAIN_VN }}
  
            #### Secrets ####
            API_KEY: ${{ secrets.API_KEY }}
            
          run: |
            cd backend
            python -m pytest